apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  releaseName: my-metrics
  chart:
    spec:
      chart: metrics-server
      version: 3.8.4
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    image:
      tag: v0.6.2
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls
