apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: ciliumhelm

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system