apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./monitoring
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure   
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system