apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      ingressClassResource:
        default: true
    defaultBackend:
      enabled: false
